{
 "title": "Benthos Studio",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "V1 Request Codes Per 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_v1_request{endpoint!=\"node_sync\",endpoint!=\"deployment_file_traces\"}[5m])*300 > 0",
     "legendFormat": "{{endpoint}} {{code}} {{method}}"
    }
   ]
  },
  {
   "title": "V1 Request Latency 99th",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (api_v1_latency{quantile=\"0.99\"})",
     "legendFormat": "{{endpoint}} 99th"
    }
   ]
  },
  {
   "title": "Node Syncs Per 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_v1_request{endpoint=\"node_sync\"}[5m])*300 > 0",
     "legendFormat": "{{endpoint}} {{code}} {{method}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"benthos_studio\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"benthos_studio\"}"
    }
   ]
  },
  { "title": "Janitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Janitor Actions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "rate(janitor_purged[5m])", "legendFormat": "Purged {{resource}}" }
   ]
  },
  {
   "title": "Janitor Run Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "janitor_run_latency", "legendFormat": "Run latency {{quantile}}" },
    { "expr": "subscriptions_sync_latency", "legendFormat": "Sub Sync latency {{quantile}}" }
   ]
  },
  { "title": "Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "V1 Request Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "api_v1_request{endpoint!=\"node_sync\",endpoint!=\"deployment_file_traces\"} > 0",
     "legendFormat": "{{endpoint}} {{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "janitor_total_sessions", "legendFormat": "Sessions" },
    { "expr": "janitor_total_organisations", "legendFormat": "Organisations" },
    { "expr": "janitor_total_users", "legendFormat": "Users" },
    { "expr": "janitor_total_deployments", "legendFormat": "Deployments" },
    { "expr": "subscriptions", "legendFormat": "Subscriptions" }
   ]
  }
 ]
}